### ISSUE TITLE
test CPLEX throws errors

### ISSUE THREAD

**Issue by mikeKAH** [jump-dev/CPLEX.jl#314] opened 2020-09-03 11:37 UTC
Hi,
`pkg> test CPLEX` throws the errors listed below. Setting: 
Julia 1.5.1, 
CPLEX.jl 0.6.6, 
CPLEX 12.9 
Ubuntu 18.04

`LazyConstraint: Error During Test at /home/user/.julia/packages/CPLEX/DgohF/test/MathOptInterface/MOI_callbacks.jl:55
  Got exception outside of a @test
  TypeError: in typeassert, expected Tuple{CPLEX.Model,Function}, got a value of type Tuple{Int64,Int64}`

`LazyConstraintCallback: Error During Test at /home/user/.julia/packages/CPLEX/DgohF/test/MathOptInterface/MOI_callbacks.jl:54
  Got exception outside of a @test
  MethodError: no method matching fieldname(::CPLEX.Optimizer, ::Int64)
  Closest candidates are:
    fieldname(!Matched::Type{var"#s9"} where var"#s9"<:Tuple, ::Integer) at reflection.jl:158
    fieldname(!Matched::DataType, ::Integer) at reflection.jl:145
    fieldname(!Matched::UnionAll, ::Integer) at reflection.jl:157
`
![image](https://user-images.githubusercontent.com/45453344/92110103-7dfbb700-edea-11ea-8fe4-4c0e2ebed682.png)

**Comment by odow** [comment] 2020-09-03 19:12
Duplicate of https://github.com/jump-dev/CPLEX.jl/issues/312

**Closed by odow** 2020-09-03 19:12 UTC
