### ISSUE TITLE
CPLEX---Warning:  Non-integral bounds for integer variables rounded.

### ISSUE THREAD

**Issue by Lewis-Liu** [jump-dev/CPLEX.jl#311] opened 2020-07-15 21:03 UTC
Hi,

I got this warning (Non-integral bounds for integer variables rounded) when calling the CPLEX solver.  

If I want to deal with this warning message, how to solve it. 

In addition, I use the CPLEX interface of python to solve the same model, this warning will not appear.

Julia version 1.4.2
CPLEX version 12.10

**Comment by odow** [comment] 2020-07-15 21:46
I don't believe this is coming from CPLEX.jl. It's probably coming from the underlying C library. Can you provide a reproducible example demonstrating the error, along with the text of the warning?

> If I want to deal with this warning message, how to solve it.

Presumably, don't have fractional bounds for your variables.

**Comment by hdavid16** [comment] 2020-07-15 21:48
I think CPLEX is simply tightening your bounds since you have integer variables, making it easier for it to solve

**Comment by hdavid16** [comment] 2020-07-15 21:53
A small example where this happens can be found in slides 12-13 https://www.google.com/url?sa=t&source=web&rct=j&url=https://www.juliaopt.org/meetings/bordeaux2018/dowson.pdf&ved=2ahUKEwiZyL65ndDqAhXVmHIEHTGgCFcQFjAAegQIAhAB&usg=AOvVaw0ZF2jah5NN4rKBeRo0A7MU&cshid=1594849609065

**Comment by Lewis-Liu** [comment] 2020-07-15 23:16
> I don't believe this is coming from CPLEX.jl. It's probably coming from the underlying C library. Can you provide a reproducible example demonstrating the error, along with the text of the warning?
> 
> > If I want to deal with this warning message, how to solve it.
> 
> Presumably, don't have fractional bounds for your variables.

In my model, there is a binary variable. And others are float variables.

Here is a simple example. There are two variables in the example, and the warning appears twice. While my model only has an array of binary type, the warning only appears once.
```
using JuMP  
using CPLEX  
model = Model(CPLEX.Optimizer)
@variable(model, b1, Bin) # binary variable
@variable(model, b2, Bin) # binary variable
@constraint(model, c1, b1 + b2 >= 1)
@objective(model, Max, 10b1-b2)
optimize!(model)
println(objective_value(model))
```

**Output**:
```
Warning:  Non-integral bounds for integer variables rounded. 
1 of 1 MIP starts provided solutions.
MIP start 'm1' defined initial solution with objective 10.0000.
Warning:  Non-integral bounds for integer variables rounded.
Tried aggregator 1 time.
MIP Presolve eliminated 1 rows and 2 columns.
All rows and columns eliminated.
Presolve time = 0.00 sec. (0.00 ticks)

Root node processing (before b&c):
  Real time             =    0.02 sec. (0.00 ticks)
Parallel b&c, 8 threads:
  Real time             =    0.00 sec. (0.00 ticks)
  Sync time (average)   =    0.00 sec.
  Wait time (average)   =    0.00 sec.
                          ------------
Total (root+branch&cut) =    0.02 sec. (0.00 ticks)
10.0
```

**Comment by odow** [comment] 2020-07-16 01:40
This is an internal CPLEX warning. You can safely ignore it. I don't know why the Python interface doesn't generate it, but the C one does.

**Comment by hdavid16** [comment] 2020-07-16 02:42
@odow 

This may warrant further investigation. I've run 3 examples of the simple IP: max x subject to x>=1 and x is binary:

1. declaring x as a binary
2. declaring x as an integer with bounds 0<=x<=1
3. declaring x as continuous (0<=x<=1) and then setting to binary

These should result in the exact same output since the model is the same. However, Case 1 gives the warning, whereas Cases 2 and 3 do not. I'm wondering if there is some round off issue (numerical precision) on the bounds with the way binary variables are declared within JuMP. Any thoughts?

```julia
using JuMP, CPLEX  

println("Using a binary")
model = Model(CPLEX.Optimizer)
@variable(model, x, Bin)
@constraint(model, x >= 1)
@objective(model, Max, x)
optimize!(model)
println(objective_value(model))

println()
println("Using an integer")
model = Model(CPLEX.Optimizer)
@variable(model, 0<=x<=1, Int)
@constraint(model, x >= 1)
@objective(model, Max, x)
optimize!(model)
println(objective_value(model))

println()
println("Converting to binary")
model = Model(CPLEX.Optimizer)
@variable(model, 0<=x<=1)
set_binary(x)
@constraint(model, x >= 1)
@objective(model, Max, x)
optimize!(model)
println(objective_value(model))

julia> 
Using a binary
Warning:  Non-integral bounds for integer variables rounded.
1 of 1 MIP starts provided solutions.
MIP start 'm1' defined initial solution with objective 1.0000.
Warning:  Non-integral bounds for integer variables rounded.
Tried aggregator 1 time.
MIP Presolve eliminated 1 rows and 1 columns.
All rows and columns eliminated.
Presolve time = 0.00 sec. (0.00 ticks)

Root node processing (before b&c):
  Real time             =    0.00 sec. (0.00 ticks)
Parallel b&c, 8 threads:
  Real time             =    0.00 sec. (0.00 ticks)
  Sync time (average)   =    0.00 sec.
  Wait time (average)   =    0.00 sec.
                          ------------
Total (root+branch&cut) =    0.00 sec. (0.00 ticks)
1.0

Using an integer
1 of 1 MIP starts provided solutions.
MIP start 'm1' defined initial solution with objective 1.0000.
Tried aggregator 1 time.
MIP Presolve eliminated 1 rows and 1 columns.
All rows and columns eliminated.
Presolve time = 0.00 sec. (0.00 ticks)

Root node processing (before b&c):
  Real time             =    0.00 sec. (0.00 ticks)
Parallel b&c, 8 threads:
  Real time             =    0.00 sec. (0.00 ticks)
  Sync time (average)   =    0.00 sec.
  Wait time (average)   =    0.00 sec.
                          ------------
Total (root+branch&cut) =    0.00 sec. (0.00 ticks)
1.0

Converting to binary
1 of 1 MIP starts provided solutions.
MIP start 'm1' defined initial solution with objective 1.0000.
Tried aggregator 1 time.
MIP Presolve eliminated 1 rows and 1 columns.
All rows and columns eliminated.
Presolve time = 0.00 sec. (0.00 ticks)

Root node processing (before b&c):
  Real time             =    0.00 sec. (0.00 ticks)
Parallel b&c, 8 threads:
  Real time             =    0.00 sec. (0.00 ticks)
  Sync time (average)   =    0.00 sec.
  Wait time (average)   =    0.00 sec.
                          ------------
Total (root+branch&cut) =    0.00 sec. (0.00 ticks)
1.0

**Comment by odow** [comment] 2020-07-16 13:56
Case 1 gives the warning because we do not specify bounds by default (so CPLEX receives `-Inf <= x <= Inf`, then rounds to `0 <= x < = 1`). 

I think this is expected behavior. 

The two cases are quite different on the JuMP side:
```Julia
@variable(model, x, Bin)
@variable(model, 0 <= x <= 1, Bin)
```
It would be weird if we had an exception for binary variables.

**Comment by mlubin** [comment] 2020-07-16 14:01
Well, we shouldn't have CPLEX printing a warning whenever someone uses binary variables.

**Comment by hdavid16** [comment] 2020-07-16 14:16
I agree. JuMP should infer the bounds on binary variables to avoid the CPLEX warning...

**Comment by Lewis-Liu** [comment] 2020-07-18 15:52
Intuitively, a binary variable should only take two integer values, 0 and 1, instead of two floating-point values, 0.0 and 1.0. When novices switch from other languages, such as Python, they will feel weird about the floating-point values ​​of such binary variables.

**Comment by odow** [comment] 2020-07-18 16:00
> Intuitively, a binary variable should only take two integer values, 0 and 1, instead of two floating-point values, 0.0 and 1.0

Solvers consider a variable binary if it is within some tolerance of 0.0 or 1.0 (typically ~10^-5). They don't work with integers. This is independent of the Julia/Python/C/etc interfaces the solvers.

**Comment by Lewis-Liu** [comment] 2020-07-18 16:25
@odow  Yes. You are right. 

Besides, after solving the model with binary variables, returning the binary variable values ​​in the form of integers 0 and 1 will be more intuitive than floating-point.

**Comment by hdavid16** [comment] 2020-07-18 17:51
I'm not sure what your discussion on floating-points and intuitiveness has to do with this. Anyways, I've moved this issue over to JuMP. https://github.com/jump-dev/JuMP.jl/issues/2288#issue-660283164.

So if you want to close this issue, you can do so. I've put it as a feature request on JuMP for the bounds on binary variables to be inferred.

**Comment by odow** [comment] 2020-07-18 18:07
I've commented in the JuMP issue that should should be fixed in the CPLEX wrapper.

**Comment by hdavid16** [comment] 2020-07-18 18:58
Makes sense.

**Comment by odow** [comment] 2020-07-18 19:43
Leaving this open until the issue is fixed in CPLEX.jl.

**Comment by Lewis-Liu** [comment] 2020-07-18 20:38
OK.

**Closed** 2020-10-05 20:49 UTC
