### ISSUE TITLE
Large overhead time even using direct_model(CPLEX.Optimizer())

### ISSUE THREAD

**Issue by ImanAlizadeh** [jump-dev/CPLEX.jl#427] opened 2023-03-28 07:18 UTC
Here is the output of CPLEX.jl:
`Version identifier: 20.1.0.0 | 2020-11-10 | 9bedb6d68
CPXPARAM_LPMethod                                4
CPXPARAM_SolutionType                            2
CPXPARAM_Barrier_ConvergeTol                     0.00050000000000000001
Tried aggregator 1 time.
DUAL formed by presolve
Aggregator has done 175104 substitutions...
LP Presolve eliminated 1901232 rows and 5050 columns.
Aggregator did 175104 substitutions.
Reduced LP has 2154158 rows, 6220910 columns, and 23773780 nonzeros.
Presolve time = 56.58 sec. (14064.24 ticks)
Symmetry aggregator did 3680424 additional substitutions.
Tried aggregator 0 times.
No LP presolve or aggregator reductions.
Presolve time = 4.63 sec. (1342.32 ticks)
Parallel mode: using up to 8 threads for barrier.
Number of nonzeros in lower triangle of A*A' = 10175381
Using Approximate Minimum Degree ordering
Total time for automatic ordering = 1.64 sec. (808.40 ticks)
Summary statistics for Cholesky factor:
  Threads                   = 8
  Rows in Factor            = 1208754
  Integer space required    = 3419240
  Total non-zeros in factor = 19491928
  Total FP ops to factor    = 392602152`

I checked the time using: @time and this is the result:
`1290.470817 seconds (832.34 M allocations: 118.687 GiB, 77.18% gc time)`
However, the solver took this amount of time:
`Total time on 8 threads = 106.17 sec. (34256.02 ticks)
Barrier time = 107.02 sec. (34956.96 ticks)`

The problem is written using @variable and @constraint like:
`@constraint(model_name, [c in 1:nCont, s in 1:nSc, t in 1:nTP, l in 1:length(idx_from_line_c[c])],
ploss_c_dict[[c,s,t,idx_from_line_c[c][l],idx_to_line_c[c][l]]]>=0)`

I appreciate if you help me on this!

**Comment by odow** [comment] 2023-03-28 17:46
Can you provide a reproducible example?

**Comment by ImanAlizadeh** [comment] 2023-03-29 08:32
Sorry, I can not provide a reproducible example. However, this is one of the time-consuming constraints. It takes 760 seconds to be generated. 
`
function power_balance_t_c(model_name)
    @constraint(model_name, active_power_balance_contin[c in 1:20, s in 1:5, t in 1:24, b in 1:300],

    boolean_func(b,bus_data_gsheet, Pg_c[c,s,t,:])
    +
    boolean_func(b,RES_bus, prof_PRES[s,t,:])
    +
    boolean_func(b,bus_data_lsheet, pen_lsh_c[c,s,t,:])
    -
    boolean_func(b,RES_bus, pen_ws_c[c,s,t,:])
    -
    boolean_func(b,nd_Str_active, p_ch_c[c,s,t,:])
    +
    boolean_func(b,nd_Str_active,p_dis_c[c,s,t,:] )
    # +
    # slack_pb_p_c[c,s,t,b]
    # -
    # slack_pb_n_c[c,s,t,b]
     ==boolean_func_injection(c,s,t,b,pinj_dict_c,node_data_contin[c][b].node_cnode_c)
     +
     boolean_func_injection(c,s,t,b,pinj_dict_c,node_data_trans[b,1].node_cnode)
     +
     boolean_func(b,bus_data_lsheet,prof_ploads[:,t] )
     +
     boolean_func(b,nd_fl,p_fl_inc_c[c,s,t,:] )
     -
     boolean_func(b,nd_fl,p_fl_dec_c[c,s,t,:] )
         )
`
where the inner functions are:
`function boolean_func(b::Int64,map, a)

    A= (a[i[1]] for i in  indexin(b,map) if ~isnothing(indexin(b,map)[1]))
    if !isempty(A)

        return a[indexin(b,map)[1]]
    else
        return 0

    end
end`

and 

`
function boolean_func_injection(c::Int64,s::Int64,t::Int64,b::Int64,pinj_dict_c,N)
    A=(pinj_dict_c[[c,s,t,b,j]] for j in N if ~isempty(N))
    if !isempty(A)

        return sum(pinj_dict_c[[c,s,t,b,j]] for j in N)
    else
        return 0
    end
end`

**Comment by odow** [comment] 2023-03-29 19:28
This seems like it is a problem with how you're constructing the problem at the JuMP level, not a bug in CPLEX.jl.

You're allocating a lot of intermediate objects that are expensive. For example, `indexin(b,map)` creates a vector, and you're calling it three times in the `boolean_func` function, and the `boolean_func` function is called 9 times for each constraint, and you have 720,000 constraints. So you're calling `indexin` 19,440,000 times.

What are `bus_data_gsheet` and `Pg_c`? You might be better off posting this as a question on the community forum, https://discourse.julialang.org/c/domain/opt/13, with a reproducible example that we can copy and paste.

**Comment by odow** [comment] 2023-04-05 22:37
Closing because this is most likely un-related to CPLEX.jl.

If you have more questions, please post on the discourse forum, https://discourse.julialang.org/c/domain/opt/13, and we can dig into the details :smile:

**Closed by odow** 2023-04-05 22:37 UTC
