### ISSUE TITLE
Support for cplex 22

### ISSUE THREAD

**Issue by chelseas** [jump-dev/CPLEX.jl#399] opened 2022-04-14 05:04 UTC
Hi, I see some commits getting this package ready for cplex 22. Is it ready for use and for the Project.toml to be updated?

**Comment by odow** [comment] 2022-04-14 08:22
Does it not work at present?

**Comment by chelseas** [comment] 2022-04-14 08:47
Oh sorry skipped a step. Dev,  edit project.toml, test?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by blegat** [comment] 2022-04-14 12:20
Hi, the Project.toml does not need to be updated as the CPLEX binary is not installed by the Pkg manager but by the following script:
https://github.com/jump-dev/CPLEX.jl/blob/16028c68d6900183cb427a5e11e12215bfd0360e/deps/build.jl#L8-L12
You an see that v22 is supported by the latest version of CPLEX.jl

**Comment by odow** [comment] 2022-04-17 20:26
> Oh sorry skipped a step. Dev,  edit project.toml, test?

No, you just need to install the latest release of CPLEX.jl.

If you already have it installed run `import Pkg; Pkg.build("CPLEX")`.

**Comment by odow** [comment] 2022-04-26 04:07
@chelseas did you get this working?

**Comment by chelseas** [comment] 2022-04-26 07:57
Thanks for checking in! I actually ended up downgrading my versions of CPLEX and using 12.10 enterprise server. Haven't tested with the newest CPLEX.jl, sorry. But thanks for letting me know! If I end up trying it, I will comment. I just needed to get something working.

**Comment by odow** [comment] 2022-04-26 09:19
Closing this for now because I'm not aware of a reason why CPLEX 22 wouldn't work (it gets tested in CI). Please re-open if you can reproduce in future.

**Closed by odow** 2022-04-26 09:19 UTC

**Comment by chelseas** [comment] 2022-10-11 08:01
I concluded from the error message I got when using cplex 22 that it's still explicitly limited in the project.toml. would I test that by devving the package, running test on it and if nothing fails then it's good to go?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by odow** [comment] 2022-10-11 19:34
> it's still explicitly limited in the project.toml

Nothing in Project.toml limits the upstream version of CPLEX that we can use.
