### ISSUE TITLE
Feasibility issue with JuMP + CPLEX on Quadratically constrained problem

### ISSUE THREAD

**Issue by gliuzzi** [jump-dev/CPLEX.jl#346] opened 2020-12-14 12:43 UTC
Hi everybody,
i am working with CPLEX through JuMP. I came across this quadraticaly constrained problem which i attach in ampl and lp file formats

[prob_error.mod.txt](https://github.com/jump-dev/JuMP.jl/files/5688772/prob_error.mod.txt)
[prob_error.lp.txt](https://github.com/jump-dev/JuMP.jl/files/5688775/prob_error.lp.txt)

I also attach a Julia script that solves the problem both using cplex and ipopt along with the JLD file containing matrices and vectors defining the problem. 

[error_test_github.jl.txt](https://github.com/jump-dev/JuMP.jl/files/5688793/error_test_github.jl.txt)
[error.jld.txt](https://github.com/jump-dev/JuMP.jl/files/5688794/error.jld.txt)

The cplex solution is infeasible whereas the ipopt solution is feasible.

Honestly, I am stuck. I would really appreciate any help or suggestion.

Thanks a lot in advance to anyone who can help.

**Comment by gliuzzi** [comment] 2020-12-15 18:42
More precisely, I use the following piece of codo to check feasibility w.r.t. linear equality constraints
```
println("Linear equality constraints:")
for i in 1:meq
	check = 0.0
	for j in 1:n
		check += Aeq[i,j]*solx[j]
	end
	check += - beq[i]
	if abs(check) > 1.e-5
		println(i," residual: ",check," VIOLATED")
	else
		println(i," residual: ",check)
	end
end
```

**Comment by odow** [comment] 2020-12-15 18:44
I've transferred this to CPLEX.jl. It could very well be a CPLEX bug. It would be helpful to have a simpler example that doesn't rely on the JLD. 

p.s. Note that CPLEX.jl is not maintained by IBM, and I won't have time to look at this in any detail before the new year.

**Comment by gliuzzi** [comment] 2020-12-15 18:59
Dear Oscar,
I thank you for your interest and your more than appreciated suggestions. 
I am almost sure this is a cplex issue not a Julia/JuMP one.
I just wanted to share the problem with the JuMP community somehow.
I am trying to open a case at IBM but it is not that easy if you use cplex through the academic initiative as i do. I'll try and see what happens.

Cheers,

      Giamp

**Comment by odow** [comment] 2021-01-25 03:00
Confirmed as a bug in CPLEX, although there are some really small coefficients so the numerics are a bit iffy. At the very least, CPLEX should complain instead of returning a solution that violates bounds.

Here's the offending MPS file: [bug_cplex.mps.txt](https://github.com/jump-dev/CPLEX.jl/files/5863888/bug_cplex.mps.txt)

```Julia
function main()
    status_p = Ref{Cint}()
    env = CPXopenCPLEX(status_p)
    stat = Ref{Cint}()
    lp = CPXcreateprob(env, stat, "")
    @assert CPXreadcopyprob(env, lp, "bug_cplex.mps.txt", "MPS") == 0
    @assert CPXqpopt(env, lp) == 0
    numcols = CPXgetnumcols(env, lp)
    x = Vector{Cdouble}(undef, numcols)
    @assert CPXgetx(env, lp, x, 0, numcols - 1) == 0
    ub = Vector{Cdouble}(undef, numcols)
    @assert CPXgetub(env, lp, ub, 0, numcols - 1) == 0
    stat = CPXgetstat(env, lp)
    buffer_str = Vector{Cchar}(undef, CPXMESSAGEBUFSIZE)
    status = unsafe_string(CPXgetstatstring(env, stat, buffer_str))
    violation = maximum(x .- ub)
    @assert CPXfreeprob(env, Ref(lp)) == 0
    CPXcloseCPLEX(Ref(env))
    @show status
    @show "Largest bound violation: $(violation)"
    return
end

julia> main()
Version identifier: 12.10.0.0 | 2019-11-26 | 843d4de
Tried aggregator 1 time.
QCP Presolve eliminated 8 rows and 0 columns.
Aggregator did 6 substitutions.
Reduced QCP has 167 rows, 157 columns, and 786 nonzeros.
Reduced QCP has 24 quadratic constraints.
Presolve time = 0.00 sec. (0.20 ticks)
Parallel mode: using up to 8 threads for barrier.

***NOTE: Found 9 dense columns.

Number of nonzeros in lower triangle of A*A' = 1664
Using Approximate Minimum Degree ordering
Total time for automatic ordering = 0.00 sec. (0.11 ticks)
Summary statistics for Cholesky factor:
  Threads                   = 8
  Rows in Factor            = 174
  Integer space required    = 514
  Total non-zeros in factor = 2527
  Total FP ops to factor    = 65311
 Itn      Primal Obj        Dual Obj  Prim Inf Upper Inf  Dual Inf Inf Ratio
   0   4.3599975e+01   5.5267851e+01  2.01e+02  0.00e+00  1.50e+02  8.25e+00
   1  -3.9579920e+01  -2.6323738e+01  2.01e+02  0.00e+00  1.50e+02  5.44e+00
   2  -1.1182548e+02  -1.0231824e+02  2.21e+02  0.00e+00  1.65e+02  5.63e+00
   3  -1.8902712e+02  -1.8388554e+02  1.51e+02  0.00e+00  1.13e+02  8.88e+00
   4  -2.1145119e+02  -2.0827291e+02  7.92e+01  0.00e+00  5.94e+01  1.38e+01
   5  -2.3407644e+02  -2.3264003e+02  4.85e+01  0.00e+00  3.64e+01  2.89e+01
   6  -2.3280120e+02  -2.3148445e+02  2.16e+01  0.00e+00  1.62e+01  2.81e+01
   7  -2.3815625e+02  -2.3760220e+02  1.92e+01  0.00e+00  1.44e+01  6.38e+01
   8  -2.4119934e+02  -2.4109052e+02  7.99e+00  0.00e+00  5.99e+00  3.06e+02
   9  -2.4188330e+02  -2.4187037e+02  1.54e+00  0.00e+00  1.15e+00  2.54e+03
  10  -2.4196647e+02  -2.4196570e+02  1.82e-01  0.00e+00  1.36e-01  4.21e+04
  11  -2.4197140e+02  -2.4197136e+02  1.09e-02  0.00e+00  8.16e-03  8.07e+05
  12  -2.4197166e+02  -2.4197165e+02  5.68e-04  0.00e+00  4.26e-04  1.18e+07
  13  -2.4197166e+02  -2.4197165e+02  3.90e-05  0.00e+00  2.92e-05  1.19e+07
status = "optimal"
"Largest bound violation: $(violation)" = "Largest bound violation: 0.5557854919701783"
```

**Comment by odow** [comment] 2021-09-07 22:09
Closing because this isn't an issue with CPLEX.jl. The CPLEX developers have been notified about it.

**Closed by odow** 2021-09-07 22:09 UTC
Labels: bug, upstream
