### ISSUE TITLE
Termination status 31

### ISSUE THREAD

**Issue by Entze** [jump-dev/CPLEX.jl#365] opened 2021-04-26 08:02 UTC
I've been using JuMP with CPLEX for a university assignment and while calculating infeasible models I received the following warning:
`
Termination status 31 is not wrapped by CPLEX.jl. CPLEX explains
│ this status as follows:
│ 
│ minimal conflict
`

This happens when I call `compute_conflict!(model)`.

Additionally it throws an ArgumentError:

`ArgumentError: ModelLike of type CPLEX.Optimizer does not support accessing the attribute MathOptInterface.ConstraintConflictStatus()
Stacktrace:
 [1] get_fallback(::CPLEX.Optimizer, ::MathOptInterface.ConstraintConflictStatus, ::MathOptInterface.ConstraintIndex{MathOptInterface.SingleVariable,MathOptInterface.Integer}) at /home/.../.julia/packages/MathOptInterface/5WwpK/src/attributes.jl:292
 [2] get(::CPLEX.Optimizer, ::MathOptInterface.ConstraintConflictStatus, ::MathOptInterface.ConstraintIndex{MathOptInterface.SingleVariable,MathOptInterface.Integer}) at /home/.../.julia/packages/MathOptInterface/5WwpK/src/attributes.jl:289
 [3] get(::MathOptInterface.Bridges.LazyBridgeOptimizer{CPLEX.Optimizer}, ::MathOptInterface.ConstraintConflictStatus, ::MathOptInterface.ConstraintIndex{MathOptInterface.SingleVariable,MathOptInterface.Integer}) at /home/.../.julia/packages/MathOptInterface/5WwpK/src/Bridges/bridge_optimizer.jl:1087
 [4] get(::MathOptInterface.Utilities.CachingOptimizer{MathOptInterface.AbstractOptimizer,MathOptInterface.Utilities.UniversalFallback{MathOptInterface.Utilities.Model{Float64}}}, ::MathOptInterface.ConstraintConflictStatus, ::MathOptInterface.ConstraintIndex{MathOptInterface.SingleVariable,MathOptInterface.Integer}) at /home/.../.julia/packages/MathOptInterface/5WwpK/src/Utilities/cachingoptimizer.jl:726
 [5] _moi_get_result(::MathOptInterface.Utilities.CachingOptimizer{MathOptInterface.AbstractOptimizer,MathOptInterface.Utilities.UniversalFallback{MathOptInterface.Utilities.Model{Float64}}}, ::MathOptInterface.ConstraintConflictStatus, ::Vararg{Any,N} where N) at /home/.../.julia/packages/JuMP/MIPb6/src/JuMP.jl:1087
 [6] get(::Model, ::MathOptInterface.ConstraintConflictStatus, ::ConstraintRef{Model,MathOptInterface.ConstraintIndex{MathOptInterface.SingleVariable,MathOptInterface.Integer},ScalarShape}) at /home/.../.julia/packages/JuMP/MIPb6/src/JuMP.jl:1132
 [7] (::JuMP.var"#76#77"{Model})(::ConstraintRef{Model,MathOptInterface.ConstraintIndex{MathOptInterface.SingleVariable,MathOptInterface.Integer},ScalarShape}) at /home/.../.julia/packages/JuMP/MIPb6/src/copy.jl:254
 [8] moi_filter_constraints at /home/.../.julia/packages/JuMP/MIPb6/src/copy.jl:125 [inlined]
 [9] filter!(::JuMP.var"#moi_filter_constraints#75"{JuMP.var"#76#77"{Model},Model}, ::Array{MathOptInterface.ConstraintIndex{MathOptInterface.SingleVariable,MathOptInterface.Integer},1}) at ./array.jl:2420
 [10] pass_constraints(::MathOptInterface.Utilities.CachingOptimizer{MathOptInterface.AbstractOptimizer,MathOptInterface.Utilities.UniversalFallback{MathOptInterface.Utilities.Model{Float64}}}, ::MathOptInterface.Utilities.CachingOptimizer{MathOptInterface.AbstractOptimizer,MathOptInterface.Utilities.UniversalFallback{MathOptInterface.Utilities.Model{Float64}}}, ::Bool, ::MathOptInterface.Utilities.IndexMap, ::Array{Type{#s137} where #s137<:MathOptInterface.AbstractScalarSet,1}, ::Array{Array{#s118,1} where #s118<:(MathOptInterface.ConstraintIndex{MathOptInterface.SingleVariable,S} where S),1}, ::Array{Type{#s144} where #s144<:MathOptInterface.AbstractVectorSet,1}, ::Array{Array{#s139,1} where #s139<:(MathOptInterface.ConstraintIndex{MathOptInterface.VectorOfVariables,S} where S),1}, ::typeof(MathOptInterface.Utilities.copy_constraints), ::typeof(MathOptInterface.set); filter_constraints::JuMP.var"#moi_filter_constraints#75"{JuMP.var"#76#77"{Model},Model}) at /home/.../.julia/packages/MathOptInterface/5WwpK/src/Utilities/copy.jl:440
 [11] default_copy_to(::MathOptInterface.Utilities.CachingOptimizer{MathOptInterface.AbstractOptimizer,MathOptInterface.Utilities.UniversalFallback{MathOptInterface.Utilities.Model{Float64}}}, ::MathOptInterface.Utilities.CachingOptimizer{MathOptInterface.AbstractOptimizer,MathOptInterface.Utilities.UniversalFallback{MathOptInterface.Utilities.Model{Float64}}}, ::Bool, ::JuMP.var"#moi_filter_constraints#75"{JuMP.var"#76#77"{Model},Model}) at /home/.../.julia/packages/MathOptInterface/5WwpK/src/Utilities/copy.jl:652
 [12] #automatic_copy_to#135 at /home/.../.julia/packages/MathOptInterface/5WwpK/src/Utilities/copy.jl:24 [inlined]
 [13] #copy_to#231 at /home/.../.julia/packages/MathOptInterface/5WwpK/src/Utilities/cachingoptimizer.jl:210 [inlined]
 [14] copy_model(::Model; filter_constraints::JuMP.var"#76#77"{Model}) at /home/.../.julia/packages/JuMP/MIPb6/src/copy.jl:132
 [15] copy_conflict at /home/.../.julia/packages/JuMP/MIPb6/src/copy.jl:257 [inlined]
`
The code I am calling all those things from is very similiar to the example in https://jump.dev/JuMP.jl/stable/reference/solutions/#JuMP.copy_conflict

Tell me if you need anymore data.

**Comment by odow** [comment] 2021-04-26 08:48
Thanks for the report. Do you have a minimal reproducible example we can run that triggers the error?

**Comment by Entze** [comment] 2021-04-26 08:59
So the following example minimally produces the warning but not the Argument Error:
```julia
using CPLEX, JuMP

model = Model(CPLEX.Optimizer)
@variable(model, x)
@constraint(model, cref, x>=2)
@constraint(model, cref2, x<=1)
optimize!(model)
compute_conflict!(model)
new_model, reference_map = copy_conflict(model) # warning produced here
```

For the argument error I have to try a bit. I am going to answer once I found a minimal example.

**Comment by Entze** [comment] 2021-04-26 09:10
I found a minimal example for the argument error: (I think any infeasible model with an Integer or Binary constrained variables produces this ArgumentError)

```julia
using CPLEX, JuMP

model = Model(CPLEX.Optimizer)
@variable(model, x, lower_bound = 0, upper_bound=1)
@variable(model, y, Bin, lower_bound = 0, upper_bound=1)
@constraint(model, x_must_be_one_half, 2 * x == 1)
@constraint(model, y_must_be_x, y == x)
optimize!(model)
compute_conflict!(model)
new_model, reference_map = copy_conflict(model) # Throws ArgumentError: ModelLike of type CPLEX.Optimizer does not support accessing the attribute MathOptInterface.ConstraintConflictStatus()
```

Let me know if you need anything else, I hope I was of service. My package versions:
```
Julia v1.4
  [a076750e] CPLEX v0.7.6
  [4076af6c] JuMP v0.21.7
```

**Comment by dourouc05** [comment] 2021-04-27 22:43
I've studied the issue a bit more, and it really looks like a design issue: JuMP, before getting any attribute about the model, will check if it was solved correctly, through `_moi_get_result`. But CPLEX returns a `CPX_STAT_CONFLICT_*` error code, which is not supposed to be handled at `MOI.TerminationStatus`. 

@odow, what would be the preferred solution for this? Either we can allow `CPX_STAT_CONFLICT_*` as correct values for `CPX_STAT_CONFLICT_*` (i.e. map these codes in `CPLEX._TERMINATION_STATUSES` to MOI codes), so that getting `MOI.TerminationStatus` does not return an error anymore. Or we add a variant on top of `MOI.is_set_by_optimize`, like `is_set_by_compute_conflict`. The second solution seems nicer to be, as the conflict statuses are not really set by `optimize`.

**Comment by odow** [comment] 2021-04-28 21:07
We should handle this in `TerminationStatus`. If a conflict exists, the termination status should be `INFEASIBLE`.

**Comment by dourouc05** [comment] 2021-04-28 23:10
I've just made a PR to add the missing status codes: https://github.com/jump-dev/CPLEX.jl/pull/366.

**Comment by odow** [comment] 2021-04-29 01:36
> ArgumentError: ModelLike of type CPLEX.Optimizer does not support accessing the attribute MathOptInterface.ConstraintConflictStatus() Stacktrace: [1] get_fallback(::CPLEX.Optimizer, ::MathOptInterface.ConstraintConflictStatus, ::MathOptInterface.ConstraintIndex{MathOptInterface.SingleVariable,MathOptInterface.Integer})

Ah. It seems that this issue is not the termination status, but the fact we are querying the integrality constraints. Does CPLEX provide info on these? E.g., that the continuous relaxation is feasible? If not, we should just return `NOT_IN_CONFLICT`.

**Comment by odow** [comment] 2021-04-29 01:37
Closed by mistake.

**Comment by dourouc05** [comment] 2021-04-30 18:27
Locally at least, https://github.com/jump-dev/CPLEX.jl/pull/367 solves the issue. Unfortunately, CPLEX doesn't tell whether an integrality constraint is part of a conflict (it looks like their solver is implemented only for the linear relaxation, even though the conflict refiner indicates that the problem is infeasible if the linear relaxation is feasible).

**Comment by dourouc05** [comment] 2021-05-01 16:12
@Entze, could you test the master version of CPLEX to see if the issue is resolved?

**Comment by Entze** [comment] 2021-05-03 10:44
> @Entze, could you test the master version of CPLEX to see if the issue is resolved?

Yes, but bear with me I have to set it up. I will report my findings.

**Comment by Entze** [comment] 2021-05-03 11:00
So I have tested the master branch with julia 1.6.
The minimal examples do longer produce a warning and the error is no longer thrown on copying the model.

On julia 1.4 however I can no longer build the package:

```julia
import Pkg
Pkg.resolve() # ERROR: Unsatisfiable requirements detected for package OpenSpecFun_jll [efe28fd5] [...]
```

The full error log is the following:

```
ERROR: Unsatisfiable requirements detected for package OpenSpecFun_jll [efe28fd5]:
 OpenSpecFun_jll [efe28fd5] log:
 ├─possible versions are: 0.5.3-0.5.4 or uninstalled
 ├─restricted to versions 0.5.4 by an explicit requirement, leaving only versions 0.5.4
 └─restricted by julia compatibility requirements to versions: 0.5.3 or uninstalled — no versions left
Stacktrace:
 [1] propagate_constraints!(::Pkg.Resolve.Graph, ::Set{Int64}; log_events::Bool) at /build/julia-98cBbp/julia-1.4.1+dfsg/usr/share/julia/stdlib/v1.4/Pkg/src/Resolve/graphtype.jl:1010
 [2] propagate_constraints! at /build/julia-98cBbp/julia-1.4.1+dfsg/usr/share/julia/stdlib/v1.4/Pkg/src/Resolve/graphtype.jl:951 [inlined] (repeats 2 times)
 [3] simplify_graph!(::Pkg.Resolve.Graph, ::Set{Int64}; clean_graph::Bool) at /build/julia-98cBbp/julia-1.4.1+dfsg/usr/share/julia/stdlib/v1.4/Pkg/src/Resolve/graphtype.jl:1465
 [4] simplify_graph! at /build/julia-98cBbp/julia-1.4.1+dfsg/usr/share/julia/stdlib/v1.4/Pkg/src/Resolve/graphtype.jl:1465 [inlined] (repeats 2 times)
 [5] resolve_versions!(::Pkg.Types.Context, ::Array{Pkg.Types.PackageSpec,1}) at /build/julia-98cBbp/julia-1.4.1+dfsg/usr/share/julia/stdlib/v1.4/Pkg/src/Operations.jl:341
 [6] up(::Pkg.Types.Context, ::Array{Pkg.Types.PackageSpec,1}, ::Pkg.Types.UpgradeLevel) at /build/julia-98cBbp/julia-1.4.1+dfsg/usr/share/julia/stdlib/v1.4/Pkg/src/Operations.jl:1165
 [7] up(::Pkg.Types.Context, ::Array{Pkg.Types.PackageSpec,1}; level::Pkg.Types.UpgradeLevel, mode::Pkg.Types.PackageMode, update_registry::Bool, kwargs::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}) at /build/julia-98cBbp/julia-1.4.1+dfsg/usr/share/julia/stdlib/v1.4/Pkg/src/API.jl:224
 [8] #up#43 at /build/julia-98cBbp/julia-1.4.1+dfsg/usr/share/julia/stdlib/v1.4/Pkg/src/API.jl:192 [inlined]
 [9] #resolve#52 at /build/julia-98cBbp/julia-1.4.1+dfsg/usr/share/julia/stdlib/v1.4/Pkg/src/API.jl:230 [inlined]
 [10] resolve at /build/julia-98cBbp/julia-1.4.1+dfsg/usr/share/julia/stdlib/v1.4/Pkg/src/API.jl:230 [inlined]
 [11] #resolve#51 at /build/julia-98cBbp/julia-1.4.1+dfsg/usr/share/julia/stdlib/v1.4/Pkg/src/API.jl:228 [inlined]
 [12] resolve() at /build/julia-98cBbp/julia-1.4.1+dfsg/usr/share/julia/stdlib/v1.4/Pkg/src/API.jl:228
 [13] top-level scope at REPL[15]:1
```

**Comment by dourouc05** [comment] 2021-05-03 18:41
I don't think the issue is related to CPLEX or JuMP, as OpenSpecFun is not a dependency for either package. Unfortunately, I'm not really good at debugging this kind of issue :(.

**Comment by odow** [comment] 2021-05-03 19:47
Run `Pkg.update()`, or delete the `Manifest.toml` file in your environment. In general, you cannot use the same manifest between Julia versions.

**Comment by Entze** [comment] 2021-05-05 12:48
I can confirm now that it works with Julia 1.4 as well, thank you for your helpful tips!

**Comment by dourouc05** [comment] 2021-05-05 19:13
Great! I'm closing the issue, then.

@odow, maybe this could be a good time to release a new version?

**Closed** 2021-05-05 19:14 UTC
Labels: Wrapper: MathOptInterface, bug
