### ISSUE TITLE
CPLEX Error  1217: No solution exists.

### ISSUE THREAD

**Issue by henriquebecker91** [jump-dev/CPLEX.jl#356] opened 2021-02-15 19:45 UTC
I am aware of #84. The error happens at CPLEX.jl 0.7.6 (CPLEX 20.1) and seem harmless, as the issue #355 I just opened.

The message appears if I call `MOI.get(model, MOI.SimplexIterations())` over a a MIP model read from an MPS. I think this may be associated to the "Dynamic Search" mode of CPLEX, so if CPLEX does no simplex iterations (because of Dynamic Search) the code correctly returns zero, but this strange message is triggered.

I annexed a small project/script that should help to reproduce the problem, given one has the solvers installed and configured: [debug_CPLEX_1217.tar.gz](https://github.com/jump-dev/CPLEX.jl/files/5983706/debug_CPLEX_1217.tar.gz) (Commenting and uncommenting the offending line should enable and disable the strange message.)

Again, I am not very worried about suppressing this, but only if there is some nastier consequence (wrong value returned, the code breaks if I am not using simplex but other LP method, etc...).

**Comment by odow** [comment] 2021-02-16 04:23
Does it return `0` or throw a Julia error? What's the stack trace?

**Comment by odow** [comment] 2021-02-16 04:59
Here's the documentation: https://www.ibm.com/support/knowledgecenter/SSSA5P_20.1.0/ilog.odms.cplex.help/refcallablelibrary/cpxapi/getitcnt.html

> If a solution exists, CPXgetitcnt returns the total iteration count. If no solution exists, CPXgetitcnt returns the value 0 (zero).

Seems fine to ignore.

**Comment by henriquebecker91** [comment] 2021-02-16 13:21
> Does it return 0 or throw a Julia error? What's the stack trace?

> the code correctly returns zero

> Why ask for simplex iterations if you don't force simplex as the method?

Two reasons:
1. I will execute multiple experiments with distinct configurations and solvers. I  use MOI/JuMP exactly because this way I do not need to write a different code for each solver and configuration. I have a list of solvers with a list of configurations inside, it executes each one and save the results.
2. Some of the experiments do not set the LP method, and let the solver choose. There is no reason for me to give up in the iteration info instead of just querying all iteration counters (i.e., for each method).

What I found off about the message is that the code finishes with an optimal solution, so it has not only an integer solution, but something that prove to it there is no better one (the solution of a relaxation). Saying just "No solution exists." is kinda odd here. I thought it is good to have this issue documented in case other people get confused. In my case, I query a lot of information, and I had no way to know from where this message was coming from before enabling and disabling the queries one by one (at a first moment I thought I could have messed up and the model was infeasible).

**Comment by odow** [comment] 2021-02-16 21:01
I assume it means "No solution [found by the simplex algorithm] exists."

Closing because this seems like expected behavior, and it's not coming from CPLEX.jl.

**Closed by odow** 2021-02-16 21:01 UTC
