### ISSUE TITLE
Precompiling CPLEX ERROR

### ISSUE THREAD

**Issue by pchatelain1** [jump-dev/CPLEX.jl#315] opened 2020-09-17 17:26 UTC
Hello, 
I  just installed CPLEX 12.10

I did

```julia
ENV["CPLEX_STUDIO_BINARIES"] = "C:/Program Files/IBM/ILOG/CPLEX_Studio1210/cplex/bin/x64_win64"
Pkg.add("CPLEX")
Pkg.build("CPLEX")
using JuMP
using CPLEX
```

This raises the following error:

```
 Info: Precompiling CPLEX [a076750e-1247-5638-91d2-ce28b192dca0]
ERROR: LoadError: LoadError: UndefVarError: CleverDicts not defined
Stacktrace:
 [1] getproperty(::Module, ::Symbol) at .\sysimg.jl:13
 [2] top-level scope at none:0
 [3] include at .\boot.jl:326 [inlined]
 [4] include_relative(::Module, ::String) at .\loading.jl:1038
 [5] include at .\sysimg.jl:29 [inlined]
 [6] include(::String) at C:\Users\Paul\.juliapro\JuliaPro_v1.1.0.1\packages\CPLEX\Hxpuk\src\CPLEX.jl:3
 [7] top-level scope at none:0
 [8] include at .\boot.jl:326 [inlined]
 [9] include_relative(::Module, ::String) at .\loading.jl:1038
 [10] include(::Module, ::String) at .\sysimg.jl:29
 [11] top-level scope at none:2
 [12] eval at .\boot.jl:328 [inlined]
 [13] eval(::Expr) at .\client.jl:404
 [14] top-level scope at .\none:3
in expression starting at C:\Users\Paul\.juliapro\JuliaPro_v1.1.0.1\packages\CPLEX\Hxpuk\src\MOI\MOI_wrapper.jl:4
in expression starting at C:\Users\Paul\.juliapro\JuliaPro_v1.1.0.1\packages\CPLEX\Hxpuk\src\CPLEX.jl:112
julia> 
```

I have JuliaPro 1.1.0.1
JuMP v0.21.3
CPLEX v0.6.5
Any idea to solve this ? 
Thank you,

**Comment by odow** [comment] 2020-09-17 20:38
What Is your output of `] st`? We have lots of issues with JuliaPro. It should be called "Julia for Enterprises behind firewalls" because it uses a fixed set of packages that are not the most up-to-date. I don't recommend. Just use the normal Julia download: https://julialang.org/downloads/#current_stable_release

**Comment by pchatelain1** [comment] 2020-09-19 16:45
Thank you for your quick reply.
Unfortunately, I have uninstalled JuliaPro so I'm unable to perform `] st`.
However, everything works fine with the last version of the normal Julia.

Best,

**Comment by blegat** [comment] 2020-09-19 17:20
I guess the issue is that we released a version of cplex using CleverDict without setting a lower bound on MOI to the version v0.9.x where it was introduced

**Comment by odow** [comment] 2020-09-24 03:32
That shouldn't be the problem. There was a lower bound:
https://github.com/jump-dev/CPLEX.jl/blob/e8157a9f080df2a5dcd2e4458eb8c052b083ae1e/Project.toml#L15

Closing because @pchatelain1 resolved their issue, and I don't think there is anything to fix in CPLEX.jl.

**Closed by odow** 2020-09-24 03:32 UTC
